NA-28/Add-edit-note-functionality
yevgeny-semak/notes-app-frontend pull request #12
Opened 2021-03-30 10:44 UTC by yevgeny-semak

2021-03-31 08:57 UTC, veranika-zakharchenia commented on src/components/note-edit.component.jsx
> +            apiInstance.get(`http://localhost:8000/api/notes/` + id)
can you move all requests to another file?

2021-03-31 09:03 UTC, veranika-zakharchenia commented on src/pages/notes.page.jsx
> +            <NoteAdd onAdd={addNote} />
could you provide a screenshot of the homepage?

2021-03-31 09:04 UTC, veranika-zakharchenia requested changes
some changes are required

2021-03-31 20:08 UTC, yevgeny-semak commented on src/components/note-edit.component.jsx
> +            apiInstance.get(`http://localhost:8000/api/notes/` + id)
done

2021-04-01 08:57 UTC, veranika-zakharchenia commented on src/api.instance.js
> +                    return apiInstance.post(`${apiHost}/api/users/token/refresh/`, {
for what reason did you add _api_ to the url?

2021-04-01 14:10 UTC, yevgeny-semak commented on src/api.instance.js
> +                    return apiInstance.post(`${apiHost}/api/users/token/refresh/`, {
since apiHost holds url for api host only
probably /api/ can be also added there

2021-04-01 15:47 UTC, merged