NA-32/Redesign header
yevgeny-semak/notes-app-frontend pull request #16
Opened 2021-04-21 16:07 UTC by yevgeny-semak

![image](https://user-images.githubusercontent.com/78854337/115585935-bfd36200-a2d4-11eb-83a8-352f117c5e70.png)

2021-04-21 16:08 UTC, yevgeny-semak commented
![image](https://user-images.githubusercontent.com/78854337/115586014-d37ec880-a2d4-11eb-9eed-124d064690e4.png)
![image](https://user-images.githubusercontent.com/78854337/115586096-e85b5c00-a2d4-11eb-9850-594da439b7b6.png)

2021-04-23 07:53 UTC, veranika-zakharchenia commented on src/components/search-box.component.jsx
> +const SearchWrap = styled.div`
wrapper

2021-04-23 07:54 UTC, veranika-zakharchenia commented on src/components/header.component.jsx
> +    background-color: #fb5;
move colors to the constants

2021-04-23 07:57 UTC, veranika-zakharchenia requested changes
NB fix comments

2021-04-23 08:34 UTC, yevgeny-semak commented on src/components/search-box.component.jsx
> +const SearchWrap = styled.div`
fixed

2021-04-23 08:34 UTC, yevgeny-semak commented on src/components/header.component.jsx
> +    background-color: #fb5;
fixed

2021-04-23 09:47 UTC, merged